import type { TradingPair } from "./types"

export const TRADING_PAIRS: TradingPair[] = [
  // OTC Pairs - Alphabetically sorted
  { symbol: "AED/CNY-OTC", type: "OTC", name: "AED/CNY OTC" },
  { symbol: "AUD/CAD-OTC", type: "OTC", name: "AUD/CAD OTC" },
  { symbol: "AUD/CHF-OTC", type: "OTC", name: "AUD/CHF OTC" },
  { symbol: "AUD/JPY-OTC", type: "OTC", name: "AUD/JPY OTC" },
  { symbol: "AUD/NZD-OTC", type: "OTC", name: "AUD/NZD OTC" },
  { symbol: "AUD/USD-OTC", type: "OTC", name: "AUD/USD OTC" },
  { symbol: "BHD/CNY-OTC", type: "OTC", name: "BHD/CNY OTC" },
  { symbol: "CAD/CHF-OTC", type: "OTC", name: "CAD/CHF OTC" },
  { symbol: "CAD/JPY-OTC", type: "OTC", name: "CAD/JPY OTC" },
  { symbol: "CHF/NOK-OTC", type: "OTC", name: "CHF/NOK OTC" },
  { symbol: "EUR/AUD-OTC", type: "OTC", name: "EUR/AUD OTC" },
  { symbol: "EUR/CAD-OTC", type: "OTC", name: "EUR/CAD OTC" },
  { symbol: "EUR/CHF-OTC", type: "OTC", name: "EUR/CHF OTC" },
  { symbol: "EUR/GBP-OTC", type: "OTC", name: "EUR/GBP OTC" },
  { symbol: "EUR/HUF-OTC", type: "OTC", name: "EUR/HUF OTC" },
  { symbol: "EUR/JPY-OTC", type: "OTC", name: "EUR/JPY OTC" },
  { symbol: "EUR/NZD-OTC", type: "OTC", name: "EUR/NZD OTC" },
  { symbol: "EUR/RUB-OTC", type: "OTC", name: "EUR/RUB OTC" },
  { symbol: "EUR/TRY-OTC", type: "OTC", name: "EUR/TRY OTC" },
  { symbol: "EUR/USD-OTC", type: "OTC", name: "EUR/USD OTC" },
  { symbol: "GBP/AUD-OTC", type: "OTC", name: "GBP/AUD OTC" },
  { symbol: "GBP/JPY-OTC", type: "OTC", name: "GBP/JPY OTC" },
  { symbol: "GBP/USD-OTC", type: "OTC", name: "GBP/USD OTC" },
  { symbol: "GOLD-OTC", type: "OTC", name: "GOLD OTC" },
  { symbol: "JOD/CNY-OTC", type: "OTC", name: "JOD/CNY OTC" },
  { symbol: "KES/USD-OTC", type: "OTC", name: "KES/USD OTC" },
  { symbol: "LBP/USD-OTC", type: "OTC", name: "LBP/USD OTC" },
  { symbol: "MAD/USD-OTC", type: "OTC", name: "MAD/USD OTC" },
  { symbol: "NGN/USD-OTC", type: "OTC", name: "NGN/USD OTC" },
  { symbol: "NZD/JPY-OTC", type: "OTC", name: "NZD/JPY OTC" },
  { symbol: "NZD/USD-OTC", type: "OTC", name: "NZD/USD OTC" },
  { symbol: "OMR/CNY-OTC", type: "OTC", name: "OMR/CNY OTC" },
  { symbol: "QAR/CNY-OTC", type: "OTC", name: "QAR/CNY OTC" },
  { symbol: "SAR/CNY-OTC", type: "OTC", name: "SAR/CNY OTC" },
  { symbol: "TND/USD-OTC", type: "OTC", name: "TND/USD OTC" },
  { symbol: "UAH/USD-OTC", type: "OTC", name: "UAH/USD OTC" },
  { symbol: "USD/ARS-OTC", type: "OTC", name: "USD/ARS OTC" },
  { symbol: "USD/BDT-OTC", type: "OTC", name: "USD/BDT OTC" },
  { symbol: "USD/BRL-OTC", type: "OTC", name: "USD/BRL OTC" },
  { symbol: "USD/CAD-OTC", type: "OTC", name: "USD/CAD OTC" },
  { symbol: "USD/CLP-OTC", type: "OTC", name: "USD/CLP OTC" },
  { symbol: "USD/CNH-OTC", type: "OTC", name: "USD/CNH OTC" },
  { symbol: "USD/COP-OTC", type: "OTC", name: "USD/COP OTC" },
  { symbol: "USD/DZD-OTC", type: "OTC", name: "USD/DZD OTC" },
  { symbol: "USD/EGP-OTC", type: "OTC", name: "USD/EGP OTC" },
  { symbol: "USD/IDR-OTC", type: "OTC", name: "USD/IDR OTC" },
  { symbol: "USD/INR-OTC", type: "OTC", name: "USD/INR OTC" },
  { symbol: "USD/JPY-OTC", type: "OTC", name: "USD/JPY OTC" },
  { symbol: "USD/MXN-OTC", type: "OTC", name: "USD/MXN OTC" },
  { symbol: "USD/MYR-OTC", type: "OTC", name: "USD/MYR OTC" },
  { symbol: "USD/PHP-OTC", type: "OTC", name: "USD/PHP OTC" },
  { symbol: "USD/PKR-OTC", type: "OTC", name: "USD/PKR OTC" },
  { symbol: "USD/RUB-OTC", type: "OTC", name: "USD/RUB OTC" },
  { symbol: "USD/SGD-OTC", type: "OTC", name: "USD/SGD OTC" },
  { symbol: "USD/THB-OTC", type: "OTC", name: "USD/THB OTC" },
  { symbol: "USD/VND-OTC", type: "OTC", name: "USD/VND OTC" },
  { symbol: "YER/USD-OTC", type: "OTC", name: "YER/USD OTC" },
  { symbol: "ZAR/USD-OTC", type: "OTC", name: "ZAR/USD OTC" },

  // Stock/Regular Pairs - Alphabetically sorted
  { symbol: "AUD/CAD", type: "STOCK", name: "AUD/CAD" },
  { symbol: "AUD/CHF", type: "STOCK", name: "AUD/CHF" },
  { symbol: "AUD/JPY", type: "STOCK", name: "AUD/JPY" },
  { symbol: "AUD/USD", type: "STOCK", name: "AUD/USD" },
  { symbol: "CAD/CHF", type: "STOCK", name: "CAD/CHF" },
  { symbol: "CAD/JPY", type: "STOCK", name: "CAD/JPY" },
  { symbol: "CHF/JPY", type: "STOCK", name: "CHF/JPY" },
  { symbol: "EUR/AUD", type: "STOCK", name: "EUR/AUD" },
  { symbol: "EUR/CAD", type: "STOCK", name: "EUR/CAD" },
  { symbol: "EUR/CHF", type: "STOCK", name: "EUR/CHF" },
  { symbol: "EUR/GBP", type: "STOCK", name: "EUR/GBP" },
  { symbol: "EUR/JPY", type: "STOCK", name: "EUR/JPY" },
  { symbol: "EUR/USD", type: "STOCK", name: "EUR/USD" },
  { symbol: "GBP/AUD", type: "STOCK", name: "GBP/AUD" },
  { symbol: "GBP/CAD", type: "STOCK", name: "GBP/CAD" },
  { symbol: "GBP/CHF", type: "STOCK", name: "GBP/CHF" },
  { symbol: "GBP/JPY", type: "STOCK", name: "GBP/JPY" },
  { symbol: "GBP/USD", type: "STOCK", name: "GBP/USD" },
  { symbol: "GOLD", type: "STOCK", name: "GOLD" },
  { symbol: "NZD/USD", type: "STOCK", name: "NZD/USD" },
  { symbol: "USD/CAD", type: "STOCK", name: "USD/CAD" },
  { symbol: "USD/CHF", type: "STOCK", name: "USD/CHF" },
  { symbol: "USD/JPY", type: "STOCK", name: "USD/JPY" },
]
